#!/usr/bin/env bash

set -e -u -x

cd $(dirname $0)/..

db=${TMPDIR:-/tmp}/bass-loop-gen/loop.db
mkdir -p "$(dirname $db)"
[ -e "$db" ] && rm "$db"

go install -tags sqlite3 github.com/golang-migrate/migrate/v4/cmd/migrate@latest
migrate -path ./migrations -database "sqlite3://${db}" up

go install github.com/xo/xo@latest
xo schema --out ./pkg/models "sqlite3://${db}"

xo query --out ./pkg/models "sqlite3://${db}" -M -B -T IndexRunsResult -2 <<EOF
  SELECT id FROM runs ORDER BY start_time DESC LIMIT 50
EOF

xo query --out ./pkg/models "sqlite3://${db}" -M -B -T FindRunResult -2 <<EOF
  SELECT id FROM runs WHERE json_extract('meta', %%path string%%) = %%value any%% ORDER BY start_time DESC LIMIT 50
EOF
