#!/usr/bin/env bash

set -e -u -x

cd $(dirname $0)/..

db=${TMPDIR:-/tmp}/bass-loop-gen/loop.db
mkdir -p "$(dirname $db)"
[ -e "$db" ] && rm "$db"

go install -tags sqlite3 github.com/golang-migrate/migrate/v4/cmd/migrate@latest
migrate -path ./migrations -database "sqlite3://${db}" up

go install github.com/xo/xo@latest
xo schema --out ./pkg/models "sqlite3://${db}"

xo query --out ./pkg/models "sqlite3://${db}" -M -B -T ThunkListing -2 <<EOF
SELECT digest, json FROM thunks
EOF
