#!/usr/bin/env bash

set -e -u -x

db=$(mktemp --tmpdir loop.db.XXXXX)

cd $(dirname $0)/..

go install -tags sqlite3 github.com/golang-migrate/migrate/v4/cmd/migrate@latest
migrate -path ./migrations -database "sqlite3://${db}" up

go install github.com/xo/xo@latest
xo schema --out ./pkg/models "sqlite3://${db}"
