package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// SchemaMigration represents a row from 'schema_migrations'.
type SchemaMigration struct {
	Version sql.NullString `json:"version"` // version
	Dirty   sql.NullBool   `json:"dirty"`   // dirty
}

// SchemaMigrationByVersion retrieves a row from 'schema_migrations' as a SchemaMigration.
//
// Generated from index 'version_unique'.
func SchemaMigrationByVersion(ctx context.Context, db DB, version sql.NullString) (*SchemaMigration, error) {
	// query
	const sqlstr = `SELECT ` +
		`version, dirty ` +
		`FROM schema_migrations ` +
		`WHERE version = $1`
	// run
	logf(sqlstr, version)
	sm := SchemaMigration{}
	if err := db.QueryRowContext(ctx, sqlstr, version).Scan(&sm.Version, &sm.Dirty); err != nil {
		return nil, logerror(err)
	}
	return &sm, nil
}
